### ISSUE TITLE
点叉后会在任务栏右下角会堆积图标

### ISSUE THREAD

**Issue by kele9527** [heerheer/XQ-Native#1]
![QQ截图20200807141434](https://user-images.githubusercontent.com/34022069/89615179-94305900-d8b8-11ea-881c-1f63e1de468e.png)
点叉后会在任务栏右下角会堆积图标
![QQ截图20200807141506](https://user-images.githubusercontent.com/34022069/89615232-b75b0880-d8b8-11ea-955c-27a1cadb773c.png)

**Comment by heerheer** [comment]
小幅度bug fix已更新上传，可以去仓库查看
